version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  stubServer:
    image: pactfoundation/pact-stub-server
    working_dir: /app
    ports:
      - 8086:8080
      - 15673:15672
    volumes:
      - $(pwd)/pacts/:/app/pacts