spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password:
  flyway:
    url: jdbc:postgresql://localhost:5432/demo
    user: postgres
    password:
    locations: filesystem:database/migrations
    schemas: public
  jpa:
    hibernate:
      ddl-auto: none
      jdbc:
        lob:
          non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
queue:
  name: demoQueue

payment-gateway:
  host: https://awesome-gateway.com
